// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/catalog/catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sneaker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sneaker) Reset() {
	*x = Sneaker{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sneaker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sneaker) ProtoMessage() {}

func (x *Sneaker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sneaker.ProtoReflect.Descriptor instead.
func (*Sneaker) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Sneaker) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sneaker) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Sneaker) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type GetAllSneakersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSneakersRequest) Reset() {
	*x = GetAllSneakersRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSneakersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSneakersRequest) ProtoMessage() {}

func (x *GetAllSneakersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSneakersRequest.ProtoReflect.Descriptor instead.
func (*GetAllSneakersRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{1}
}

type GetAllSneakersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sneakers      []*Sneaker             `protobuf:"bytes,1,rep,name=sneakers,proto3" json:"sneakers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllSneakersReply) Reset() {
	*x = GetAllSneakersReply{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllSneakersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllSneakersReply) ProtoMessage() {}

func (x *GetAllSneakersReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllSneakersReply.ProtoReflect.Descriptor instead.
func (*GetAllSneakersReply) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetAllSneakersReply) GetSneakers() []*Sneaker {
	if x != nil {
		return x.Sneakers
	}
	return nil
}

type GetSneakerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSneakerByIDRequest) Reset() {
	*x = GetSneakerByIDRequest{}
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSneakerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSneakerByIDRequest) ProtoMessage() {}

func (x *GetSneakerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_catalog_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSneakerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetSneakerByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_catalog_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetSneakerByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_catalog_catalog_proto protoreflect.FileDescriptor

const file_proto_catalog_catalog_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/catalog/catalog.proto\x12\acatalog\x1a\x1bgoogle/protobuf/empty.proto\"E\n" +
	"\aSneaker\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\"\x17\n" +
	"\x15GetAllSneakersRequest\"C\n" +
	"\x13GetAllSneakersReply\x12,\n" +
	"\bsneakers\x18\x01 \x03(\v2\x10.catalog.SneakerR\bsneakers\"'\n" +
	"\x15GetSneakerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xdb\x01\n" +
	"\aCatalog\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00\x12P\n" +
	"\x0eGetAllSneakers\x12\x1e.catalog.GetAllSneakersRequest\x1a\x1c.catalog.GetAllSneakersReply\"\x00\x12D\n" +
	"\x0eGetSneakerByID\x12\x1e.catalog.GetSneakerByIDRequest\x1a\x10.catalog.Sneaker\"\x00B\x1bZ\x19hotsneakers/proto/catalogb\x06proto3"

var (
	file_proto_catalog_catalog_proto_rawDescOnce sync.Once
	file_proto_catalog_catalog_proto_rawDescData []byte
)

func file_proto_catalog_catalog_proto_rawDescGZIP() []byte {
	file_proto_catalog_catalog_proto_rawDescOnce.Do(func() {
		file_proto_catalog_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)))
	})
	return file_proto_catalog_catalog_proto_rawDescData
}

var file_proto_catalog_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_catalog_catalog_proto_goTypes = []any{
	(*Sneaker)(nil),               // 0: catalog.Sneaker
	(*GetAllSneakersRequest)(nil), // 1: catalog.GetAllSneakersRequest
	(*GetAllSneakersReply)(nil),   // 2: catalog.GetAllSneakersReply
	(*GetSneakerByIDRequest)(nil), // 3: catalog.GetSneakerByIDRequest
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_proto_catalog_catalog_proto_depIdxs = []int32{
	0, // 0: catalog.GetAllSneakersReply.sneakers:type_name -> catalog.Sneaker
	4, // 1: catalog.Catalog.Ping:input_type -> google.protobuf.Empty
	1, // 2: catalog.Catalog.GetAllSneakers:input_type -> catalog.GetAllSneakersRequest
	3, // 3: catalog.Catalog.GetSneakerByID:input_type -> catalog.GetSneakerByIDRequest
	4, // 4: catalog.Catalog.Ping:output_type -> google.protobuf.Empty
	2, // 5: catalog.Catalog.GetAllSneakers:output_type -> catalog.GetAllSneakersReply
	0, // 6: catalog.Catalog.GetSneakerByID:output_type -> catalog.Sneaker
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_catalog_catalog_proto_init() }
func file_proto_catalog_catalog_proto_init() {
	if File_proto_catalog_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_catalog_catalog_proto_rawDesc), len(file_proto_catalog_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_catalog_catalog_proto_goTypes,
		DependencyIndexes: file_proto_catalog_catalog_proto_depIdxs,
		MessageInfos:      file_proto_catalog_catalog_proto_msgTypes,
	}.Build()
	File_proto_catalog_catalog_proto = out.File
	file_proto_catalog_catalog_proto_goTypes = nil
	file_proto_catalog_catalog_proto_depIdxs = nil
}
