// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/catalog/catalog.proto

package catalog

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Catalog_Ping_FullMethodName           = "/catalog.Catalog/Ping"
	Catalog_GetAllSneakers_FullMethodName = "/catalog.Catalog/GetAllSneakers"
	Catalog_GetSneakerByID_FullMethodName = "/catalog.Catalog/GetSneakerByID"
	Catalog_CreateSneaker_FullMethodName  = "/catalog.Catalog/CreateSneaker"
	Catalog_UpdateSneaker_FullMethodName  = "/catalog.Catalog/UpdateSneaker"
)

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogClient interface {
	Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAllSneakers(ctx context.Context, in *GetAllSneakersRequest, opts ...grpc.CallOption) (*GetAllSneakersResponse, error)
	GetSneakerByID(ctx context.Context, in *GetSneakerByIDRequest, opts ...grpc.CallOption) (*GetSneakerByIDResponse, error)
	CreateSneaker(ctx context.Context, in *CreateSneakerRequest, opts ...grpc.CallOption) (*CreateSneakerResponse, error)
	UpdateSneaker(ctx context.Context, in *UpdateSneakerRequest, opts ...grpc.CallOption) (*UpdateSneakerResponse, error)
}

type catalogClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogClient(cc grpc.ClientConnInterface) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) Ping(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Catalog_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetAllSneakers(ctx context.Context, in *GetAllSneakersRequest, opts ...grpc.CallOption) (*GetAllSneakersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllSneakersResponse)
	err := c.cc.Invoke(ctx, Catalog_GetAllSneakers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetSneakerByID(ctx context.Context, in *GetSneakerByIDRequest, opts ...grpc.CallOption) (*GetSneakerByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSneakerByIDResponse)
	err := c.cc.Invoke(ctx, Catalog_GetSneakerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) CreateSneaker(ctx context.Context, in *CreateSneakerRequest, opts ...grpc.CallOption) (*CreateSneakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSneakerResponse)
	err := c.cc.Invoke(ctx, Catalog_CreateSneaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpdateSneaker(ctx context.Context, in *UpdateSneakerRequest, opts ...grpc.CallOption) (*UpdateSneakerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSneakerResponse)
	err := c.cc.Invoke(ctx, Catalog_UpdateSneaker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
// All implementations must embed UnimplementedCatalogServer
// for forward compatibility.
type CatalogServer interface {
	Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	GetAllSneakers(context.Context, *GetAllSneakersRequest) (*GetAllSneakersResponse, error)
	GetSneakerByID(context.Context, *GetSneakerByIDRequest) (*GetSneakerByIDResponse, error)
	CreateSneaker(context.Context, *CreateSneakerRequest) (*CreateSneakerResponse, error)
	UpdateSneaker(context.Context, *UpdateSneakerRequest) (*UpdateSneakerResponse, error)
	mustEmbedUnimplementedCatalogServer()
}

// UnimplementedCatalogServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServer struct{}

func (UnimplementedCatalogServer) Ping(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedCatalogServer) GetAllSneakers(context.Context, *GetAllSneakersRequest) (*GetAllSneakersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllSneakers not implemented")
}
func (UnimplementedCatalogServer) GetSneakerByID(context.Context, *GetSneakerByIDRequest) (*GetSneakerByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSneakerByID not implemented")
}
func (UnimplementedCatalogServer) CreateSneaker(context.Context, *CreateSneakerRequest) (*CreateSneakerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSneaker not implemented")
}
func (UnimplementedCatalogServer) UpdateSneaker(context.Context, *UpdateSneakerRequest) (*UpdateSneakerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSneaker not implemented")
}
func (UnimplementedCatalogServer) mustEmbedUnimplementedCatalogServer() {}
func (UnimplementedCatalogServer) testEmbeddedByValue()                 {}

// UnsafeCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServer will
// result in compilation errors.
type UnsafeCatalogServer interface {
	mustEmbedUnimplementedCatalogServer()
}

func RegisterCatalogServer(s grpc.ServiceRegistrar, srv CatalogServer) {
	// If the following call panics, it indicates UnimplementedCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Catalog_ServiceDesc, srv)
}

func _Catalog_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).Ping(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetAllSneakers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllSneakersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetAllSneakers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_GetAllSneakers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetAllSneakers(ctx, req.(*GetAllSneakersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetSneakerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSneakerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetSneakerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_GetSneakerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetSneakerByID(ctx, req.(*GetSneakerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_CreateSneaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSneakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).CreateSneaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_CreateSneaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).CreateSneaker(ctx, req.(*CreateSneakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpdateSneaker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSneakerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpdateSneaker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_UpdateSneaker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpdateSneaker(ctx, req.(*UpdateSneakerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalog_ServiceDesc is the grpc.ServiceDesc for Catalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalog.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Catalog_Ping_Handler,
		},
		{
			MethodName: "GetAllSneakers",
			Handler:    _Catalog_GetAllSneakers_Handler,
		},
		{
			MethodName: "GetSneakerByID",
			Handler:    _Catalog_GetSneakerByID_Handler,
		},
		{
			MethodName: "CreateSneaker",
			Handler:    _Catalog_CreateSneaker_Handler,
		},
		{
			MethodName: "UpdateSneaker",
			Handler:    _Catalog_UpdateSneaker_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/catalog/catalog.proto",
}
