// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/auction/auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AuctionId     int64                  `protobuf:"varint,3,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bid) Reset() {
	*x = Bid{}
	mi := &file_proto_auction_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{0}
}

func (x *Bid) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Bid) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Bid) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *Bid) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bid) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Auction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SneakerId     int64                  `protobuf:"varint,2,opt,name=sneaker_id,json=sneakerId,proto3" json:"sneaker_id,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auction) Reset() {
	*x = Auction{}
	mi := &file_proto_auction_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{1}
}

func (x *Auction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Auction) GetSneakerId() int64 {
	if x != nil {
		return x.SneakerId
	}
	return 0
}

func (x *Auction) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Auction) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type CreateAuctionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SneakerId     int64                  `protobuf:"varint,1,opt,name=sneaker_id,json=sneakerId,proto3" json:"sneaker_id,omitempty"`
	CurrentPrice  int64                  `protobuf:"varint,2,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionReq) Reset() {
	*x = CreateAuctionReq{}
	mi := &file_proto_auction_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionReq) ProtoMessage() {}

func (x *CreateAuctionReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionReq.ProtoReflect.Descriptor instead.
func (*CreateAuctionReq) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuctionReq) GetSneakerId() int64 {
	if x != nil {
		return x.SneakerId
	}
	return 0
}

func (x *CreateAuctionReq) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *CreateAuctionReq) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

type CreateAuctionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuctionResp) Reset() {
	*x = CreateAuctionResp{}
	mi := &file_proto_auction_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionResp) ProtoMessage() {}

func (x *CreateAuctionResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionResp.ProtoReflect.Descriptor instead.
func (*CreateAuctionResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAuctionResp) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

type GetAuctionDetailsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionDetailsReq) Reset() {
	*x = GetAuctionDetailsReq{}
	mi := &file_proto_auction_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionDetailsReq) ProtoMessage() {}

func (x *GetAuctionDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionDetailsReq.ProtoReflect.Descriptor instead.
func (*GetAuctionDetailsReq) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuctionDetailsReq) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

type GetAuctionDetailsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auction       *Auction               `protobuf:"bytes,1,opt,name=auction,proto3" json:"auction,omitempty"`
	Bids          []*Bid                 `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuctionDetailsResp) Reset() {
	*x = GetAuctionDetailsResp{}
	mi := &file_proto_auction_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuctionDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuctionDetailsResp) ProtoMessage() {}

func (x *GetAuctionDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuctionDetailsResp.ProtoReflect.Descriptor instead.
func (*GetAuctionDetailsResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuctionDetailsResp) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

func (x *GetAuctionDetailsResp) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

type MakeBidReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     int64                  `protobuf:"varint,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBidReq) Reset() {
	*x = MakeBidReq{}
	mi := &file_proto_auction_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidReq) ProtoMessage() {}

func (x *MakeBidReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidReq.ProtoReflect.Descriptor instead.
func (*MakeBidReq) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{6}
}

func (x *MakeBidReq) GetAuctionId() int64 {
	if x != nil {
		return x.AuctionId
	}
	return 0
}

func (x *MakeBidReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MakeBidReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type MakeBidResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MakeBidResp) Reset() {
	*x = MakeBidResp{}
	mi := &file_proto_auction_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MakeBidResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakeBidResp) ProtoMessage() {}

func (x *MakeBidResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakeBidResp.ProtoReflect.Descriptor instead.
func (*MakeBidResp) Descriptor() ([]byte, []int) {
	return file_proto_auction_auction_proto_rawDescGZIP(), []int{7}
}

var File_proto_auction_auction_proto protoreflect.FileDescriptor

const file_proto_auction_auction_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/auction/auction.proto\x12\aauction\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x03Bid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x03 \x01(\x03R\tauctionId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x90\x01\n" +
	"\aAuction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"sneaker_id\x18\x02 \x01(\x03R\tsneakerId\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x03R\fcurrentPrice\x121\n" +
	"\x06end_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"\x89\x01\n" +
	"\x10CreateAuctionReq\x12\x1d\n" +
	"\n" +
	"sneaker_id\x18\x01 \x01(\x03R\tsneakerId\x12#\n" +
	"\rcurrent_price\x18\x02 \x01(\x03R\fcurrentPrice\x121\n" +
	"\x06end_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\"2\n" +
	"\x11CreateAuctionResp\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\"5\n" +
	"\x14GetAuctionDetailsReq\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\"e\n" +
	"\x15GetAuctionDetailsResp\x12*\n" +
	"\aauction\x18\x01 \x01(\v2\x10.auction.AuctionR\aauction\x12 \n" +
	"\x04bids\x18\x02 \x03(\v2\f.auction.BidR\x04bids\"\\\n" +
	"\n" +
	"MakeBidReq\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\x03R\tauctionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\r\n" +
	"\vMakeBidResp2\x9a\x02\n" +
	"\x0eAuctionService\x126\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\rCreateAuction\x12\x19.auction.CreateAuctionReq\x1a\x1a.auction.CreateAuctionResp\x12R\n" +
	"\x11GetAuctionDetails\x12\x1d.auction.GetAuctionDetailsReq\x1a\x1e.auction.GetAuctionDetailsResp\x124\n" +
	"\aMakeBid\x12\x13.auction.MakeBidReq\x1a\x14.auction.MakeBidRespB\x1bZ\x19hotsneakers/proto/auctionb\x06proto3"

var (
	file_proto_auction_auction_proto_rawDescOnce sync.Once
	file_proto_auction_auction_proto_rawDescData []byte
)

func file_proto_auction_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_auction_proto_rawDesc), len(file_proto_auction_auction_proto_rawDesc)))
	})
	return file_proto_auction_auction_proto_rawDescData
}

var file_proto_auction_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_auction_auction_proto_goTypes = []any{
	(*Bid)(nil),                   // 0: auction.Bid
	(*Auction)(nil),               // 1: auction.Auction
	(*CreateAuctionReq)(nil),      // 2: auction.CreateAuctionReq
	(*CreateAuctionResp)(nil),     // 3: auction.CreateAuctionResp
	(*GetAuctionDetailsReq)(nil),  // 4: auction.GetAuctionDetailsReq
	(*GetAuctionDetailsResp)(nil), // 5: auction.GetAuctionDetailsResp
	(*MakeBidReq)(nil),            // 6: auction.MakeBidReq
	(*MakeBidResp)(nil),           // 7: auction.MakeBidResp
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_proto_auction_auction_proto_depIdxs = []int32{
	8, // 0: auction.Bid.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: auction.Auction.end_at:type_name -> google.protobuf.Timestamp
	8, // 2: auction.CreateAuctionReq.end_at:type_name -> google.protobuf.Timestamp
	1, // 3: auction.GetAuctionDetailsResp.auction:type_name -> auction.Auction
	0, // 4: auction.GetAuctionDetailsResp.bids:type_name -> auction.Bid
	9, // 5: auction.AuctionService.Ping:input_type -> google.protobuf.Empty
	2, // 6: auction.AuctionService.CreateAuction:input_type -> auction.CreateAuctionReq
	4, // 7: auction.AuctionService.GetAuctionDetails:input_type -> auction.GetAuctionDetailsReq
	6, // 8: auction.AuctionService.MakeBid:input_type -> auction.MakeBidReq
	9, // 9: auction.AuctionService.Ping:output_type -> google.protobuf.Empty
	3, // 10: auction.AuctionService.CreateAuction:output_type -> auction.CreateAuctionResp
	5, // 11: auction.AuctionService.GetAuctionDetails:output_type -> auction.GetAuctionDetailsResp
	7, // 12: auction.AuctionService.MakeBid:output_type -> auction.MakeBidResp
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_auction_auction_proto_init() }
func file_proto_auction_auction_proto_init() {
	if File_proto_auction_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_auction_proto_rawDesc), len(file_proto_auction_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auction_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_auction_proto_depIdxs,
		MessageInfos:      file_proto_auction_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_auction_proto = out.File
	file_proto_auction_auction_proto_goTypes = nil
	file_proto_auction_auction_proto_depIdxs = nil
}
