name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v6 # скачивает код из репы в runner

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache: true 

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Get Tools
        run: make tools

      - name: Lint
        run: make lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        version: ['1.24', '1.25', '1.26']
    steps:
      - name: Checkout 
        uses: actions/checkout@v6 

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{matrix.version}}
          cache: true 

      - name: Build
        run: |
          cd sneakers-services
          go build ./...
  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ['1.24', '1.25', '1.26']
    steps:
      - name: Checkout 
        uses: actions/checkout@v6 

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: ${{matrix.version}}
          cache: true 

      - name: Test
        run: make test

      - name: Dump docker logs on failure
        if: failure()
        run: docker compose logs